export const HEADING_OBJ = {
    particulars: 'Particulars',
    pat: 'PAT',
    depAndAmortisation: 'Depn and Amortisation',
    onCashItems: 'Other Non Cash items',
    nca: 'Change in NCA',
    defferedTaxAssets: 'Add/Less: Deferred Tax Assets(Net)',
    netCashFlow: 'Net Cash Flow',
    fixedAssets: 'Change in fixed assets',
    fcff: 'FCFF',
    discountingPeriod: 'Discounting Period (Mid Year)',
    discountingFactor: 'Discounting Factor',             //  '@WACCAT' removed this
    presentFCFF: 'Present Value of FCFF',
    sumOfCashFlows: 'Sum of Cash Flows',
    debtOnDate: 'Less: Debt as on Date',
    cashEquivalents: 'Add: Cash & Cash Equivalents',
    surplusAssets: 'Add: Surplus Assets/Investments',
    otherAdj: 'Add/Less: Other Adjustments(if any)',
    equityValue: 'Equity Value',
    noOfShares: 'No. of Shares',
    valuePerShare: 'Value per Share',
  };